apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-cards
  annotations:
    meta.crossplane.io/maintainer: Aaron Eaton <mr@aaroneaton.com>
    meta.crossplane.io/source: github.com/aaronme/provider-cards
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A template that can be used to create Crossplane providers.
spec:
  controller:
    image: DOCKER_REGISTRY/provider-cards-controller:VERSION
